<hr style="height:2px;border:none"/>
<h1 align='center'> INF-280 Estadística Computacional II-2022 </h1>

<H3 align='center'> Tema 7 - Estimación de Intervalos de Confianza  </H3>

\


Nombre del equipo: 

Integrantes:


*   Nombre Integrante 1 - ROL - [video](https://youtu.be/A6O67uLJfcQ)
*   Nombre Integrante 2 - ROL - [video](https://youtu.be/A6O67uLJfcQ)
*   Nombre Integrante 3 - ROL - [video](https://youtu.be/A6O67uLJfcQ)


*Recuerden que si su equipo se llama "El ritmo no perdona", entonces el nombre del archivo a subir debe ser T7_El_ritmo_no_perdona.ipynb*


### **Formalidades**  
* Es posible utilizar apuntes, libros, papers, ejemplos y cualquier otro material que desee de internet, pero debe ser usted quien desarrolle los ejercicios y comente los resultados en el Notebook que entregará. 
* Se permite el uso de las librerías: pandas, numpy, matplotlib y seaborn. Si desea utilizar otra librería debe indicar cómo instalarla.
* Se debe trabajar en grupos de **dos o tres personas**, las cuales deberán estar inscritas a través de __[Aula](https://aula.usm.cl/)__.
* Además del Notebook, deberán entregar un video explicando lo que hizo, paso a paso, como en los ejemplos entregados en AULA. Este vídeo es **individual**, es decir, cada integrante debe hacerlo por separado (debiendo utilizar el mismo Jupyter Notebook). El video puede ser subido a una plataforma externa como Youtube, Google Drive, ó Dropbox. El **link a compartir** (*visible para cualquier usuario con el link*) debe ir dentro del Notebook.
* La nota de esta actividad es grupal.


<hr style="height:2px;border:none"/>

### **Entrega** 
* **Formato**: Se debe realizar una **única** entrega por grupo (un representate del grupo) a través de  __[**Aula**](https://aula.usm.cl/)__.
* **Archivo**: El nombre del archivo a subir debe ser **T7_Nombre_Del_Equipo.ipynb**, por ejemplo, si su equipo se llama "El ritmo no perdona", entonces el nombre del archivo debe ser **T7_El_ritmo_no_perdona.ipynb**
* **Archivo**: Sus respuestas deben ser entregadas en forma de Jupyter Notebook, incluyendo **todos links** a los vídeos explicativos, uno por cada integrante.
    * **Vídeo**: Debe grabar la pantalla (Jupyter Notebok) donde se realiza la explicación de la actividad, con una duración máxima de 25 minutos.
* **Fecha límite**: Domingo 27 de Noviembre a las 23:59

<hr style="height:2px;border:none"/>

### **Descuentos**

* Se descontarán 5 puntos si el nombre del archivo subido no sigue el formato señalado.
* Se descontarán 10 puntos por cada hora de atraso en la entrega.
* Todos los gráficos que realicen deben contener los nombres de las variables en los ejes. Se descontarán 3 puntos por cada nombre faltante.

<hr style="height:2px;border:none"/>

<table align='left'>
<tr>
<td><img src='https://as01.epimg.net/deporteyvida/imagenes/2017/10/28/portada/1509177885_209365_1509178036_noticia_normal.jpg' width='650'/> </td>
</tr>
</table>

## Contexto

Las enfermedades cardiovasculares (ECV) son la principal causa de muerte en todo el mundo y se cobran aproximadamente 17,9 millones de vidas al año, lo que representa el 31 % de todas las muertes en todo el mundo. Cuatro de cada 5 muertes por ECV se deben a ataques cardíacos y accidentes cerebrovasculares, y un tercio de estas muertes ocurren prematuramente en personas menores de 70 años. 

La insuficiencia cardíaca es un evento común causado por ECV. Por esto, se ha construido un dataset llamado `heart.csv`, el cual contiene 11 características que pueden usarse para predecir una posible enfermedad cardíaca. Dichas características se detallan a continuación:


1.   `Age`: age of the patient [years]
2.   `Sex`: sex of the patient [M: Male, F: Female]
3.   `ChestPainType`: chest pain type [TA: Typical Angina, ATA: Atypical Angina, NAP: Non-Anginal Pain, ASY: Asymptomatic]
4.   `RestingBP`: resting blood pressure [mm Hg]
5.   `Cholesterol`: serum cholesterol [mm/dl]
6.   `FastingBS`: fasting blood sugar [1: if FastingBS > 120 mg/dl, 0: otherwise]
7.   `RestingECG`: resting electrocardiogram results [Normal: Normal, ST: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV), LVH: showing probable or definite left ventricular hypertrophy by Estes' criteria]
8.   `MaxHR`: maximum heart rate achieved [Numeric value between 60 and 202]
9.   `ExerciseAngina`: exercise-induced angina [Y: Yes, N: No]
10.  `Oldpeak`: oldpeak = ST [Numeric value measured in depression]
11.  `ST_Slope`: the slope of the peak exercise ST segment [Up: upsloping, Flat: flat, Down: downsloping]
12.  `HeartDisease`: output class [1: heart disease, 0: Normal]

# Librerías

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns; sns.set()
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Datos

In [ ]:
data = pd.read_csv("heart.csv")
data

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

# Preguntas

Para las siguientes preguntas considere un nivel de confianza del **$95\%$**, a menos que se indique lo contrario.


1. Se piensa que la edad es un factor importante a la hora de determinar si una persona tiene una enfermedad al corazón(HeartDisease=1). En particular, se cree que las mujeres tienden a presentar una enfermedad al corazón a una edad mayor que los hombres. ¿Se puede afirmar que la edad media de las mujeres que tienen una enfermedad al corazón es mayor que la edad media de los hombres con una enfermedad al corazón? **(15 pts)**
2. Determine qué ocurre con su respuesta de la pregunta anterior a medida que $α$ aumenta entre 0 y 1. **(10 pts)**
3. Se está realizando una campaña preventiva contra las enfermedades al corazón, donde se ha observado que estas enfermedades afectan principalmente a personas mayores de 50 años. Sin embargo, se busca determinar si afecta más a los hombres o a las mujeres, o bien afecta a ambos sexos por igual. Considerando solamente a las personas mayores de 50 años, determine si la proporción de hombres con enfermedades al corazón es mayor que la proporción de mujeres con enfermedades al corazón. **(15 pts)**
4. Determine si la media del colesterol de los hombres "sanos"(HeartDisease=0) es mayor que la media del colesterol de las mujeres "sanas". Además, analice lo que ocurre con sus varianzas y concluya al respecto. **(20 pts)**. **IMPORTANTE: No considere los datos que tengan Cholesterol=0**
5. Se cree que la media de la presión arterial durante el reposo (RestingBP) suele ser mayor en personas con enfermedades al corazón (HeartDisease=1). Para las siguiente preguntas **considere un nivel de confianza del $99.5\%$. Además, No considere los datos que tengan RestingBP=0**

    > a) Determine si la afirmación es verdadera considerando solamente a las mujeres. En caso de no ser cierta, ¿Cuál es el valor mínimo de $\alpha$ para que la afirmación sea verdadera? **(5 pts)**

    > b) Determine si la afirmación es verdadera considerando solamente a los hombres. En caso de no ser cierta, ¿Cuál es el valor mínimo de $\alpha$ para que la afirmación sea verdadera? **(5 pts)**

    > c) Determine si la afirmación es verdadera para todas las personas. En caso de no ser cierta, ¿Cuál es el valor mínimo de $\alpha$ para que la afirmación sea verdadera? **(5 pts)**

6.  El dolor en el pecho al realizar ejercicios (ExerciseAngina='Y') es un síntoma que se suele presentar en personas con enfermedades al corazón, ya que el corazón de estas personas no recibe suficiente sangre oxigenada.
    
    > a) Considerando solamente a las personas **con** enfermedades al corazón, ¿Se puede afirmar que la proporción de personas con dolor en el pecho cuando realizan ejercicios (ExerciseAngina='Y')` es mayor al 50%?, ¿Cuál es el máximo nivel de confianza con el cual se cumple esta afirmación? **(15 pts)**

    > b) ¿Qué ocurre si solamente se consideran a las mujeres con enfermedades al corazón en la pregunta a)? **(5 pts)**

    > c) ¿Qué ocurre si solamente se consideran a los hombres con enfermedades al corazón en la pregunta a)? **(5 pts)**